### ISSUE TITLE
offer画面の仮開発

### ISSUE THREAD

**Issue by guchio33** [jphacks/C_2213#29]

**Comment by Rei-Suzuki1729** [comment]
offers.vueっていじりました？？

**Comment by guchio33** [comment]
ページ少し作ってたぐらいです！
もし、れいさんも作っていただいていたなら、そっち優先しますよ！

**Comment by Rei-Suzuki1729** [comment]
git pullしても offer.vueが変化がないのに、ボタンがあるので、どこに書いたのかなと思いまして

**Comment by guchio33** [comment]
offer.vue今作成しているので少々お待ちください！
13時ごろにPRしますね

**Comment by Rei-Suzuki1729** [comment]
> offer.vue今作成しているので少々お待ちください！ 13時ごろにPRしますね

了解です。処理だけこっちで書きます。
